use strict;
use utf8;
use warnings;
package SoundEffect;

our @list = [
  {
    'path' => 'On-Jin/kan/お寺の鐘.mp3',
    'shortName' => 'お寺の鐘',
    'durationSeconds' => 20,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/kan/ししおどし.mp3',
    'shortName' => 'ししおどし',
    'durationSeconds' => 1,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/kan/ししおどし（響く）.mp3',
    'shortName' => 'ししおどし（響く）',
    'durationSeconds' => 2,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/kan/オフィスのざわめき.mp3',
    'shortName' => 'オフィスのざわめき',
    'durationSeconds' => 60,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/kan/クラブ・ディスコ・キャバクラ店内.mp3',
    'shortName' => 'クラブ・ディスコ・キャバクラ店内',
    'durationSeconds' => 28,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/kan/ゲームセンター.mp3',
    'shortName' => 'ゲームセンター',
    'durationSeconds' => 31,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/kan/コンビニ・入店チャイム01.mp3',
    'shortName' => 'コンビニ・入店チャイム01',
    'durationSeconds' => 6,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/kan/コンビニ・入店チャイム02.mp3',
    'shortName' => 'コンビニ・入店チャイム02',
    'durationSeconds' => 6,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/kan/チャペルの鐘01.mp3',
    'shortName' => 'チャペルの鐘01',
    'durationSeconds' => 8,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/kan/チャペルの鐘02.mp3',
    'shortName' => 'チャペルの鐘02',
    'durationSeconds' => 19,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/kan/作業現場（足場組み）.mp3',
    'shortName' => '作業現場（足場組み）',
    'durationSeconds' => 30,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/kan/地震・建物内.mp3',
    'shortName' => '地震・建物内',
    'durationSeconds' => 11,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/kan/夜中の情景.mp3',
    'shortName' => '夜中の情景',
    'durationSeconds' => 23,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/kan/大風車.mp3',
    'shortName' => '大風車',
    'durationSeconds' => 28,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/kan/天候・吹雪.mp3',
    'shortName' => '天候・吹雪',
    'durationSeconds' => 14,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/kan/天候・嵐・台風（木々）.mp3',
    'shortName' => '天候・嵐・台風（木々）',
    'durationSeconds' => 28,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/kan/天候・嵐・台風（雨）.mp3',
    'shortName' => '天候・嵐・台風（雨）',
    'durationSeconds' => 28,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/kan/天候・嵐・雷雨.mp3',
    'shortName' => '天候・嵐・雷雨',
    'durationSeconds' => 28,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/kan/天候・強風.mp3',
    'shortName' => '天候・強風',
    'durationSeconds' => 22,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/kan/天候・荒野の風.mp3',
    'shortName' => '天候・荒野の風',
    'durationSeconds' => 29,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/kan/天候・雨01.mp3',
    'shortName' => '天候・雨01',
    'durationSeconds' => 30,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/kan/天候・雨02.mp3',
    'shortName' => '天候・雨02',
    'durationSeconds' => 30,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/kan/天候・雨03.mp3',
    'shortName' => '天候・雨03',
    'durationSeconds' => 30,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/kan/天候・雨04.mp3',
    'shortName' => '天候・雨04',
    'durationSeconds' => 30,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/kan/天候・雨05.mp3',
    'shortName' => '天候・雨05',
    'durationSeconds' => 30,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/kan/天候・雨06.mp3',
    'shortName' => '天候・雨06',
    'durationSeconds' => 30,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/kan/天候・雷01.mp3',
    'shortName' => '天候・雷01',
    'durationSeconds' => 4,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/kan/天候・雷02（遠く）.mp3',
    'shortName' => '天候・雷02（遠く）',
    'durationSeconds' => 65,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/kan/天候・雷03.mp3',
    'shortName' => '天候・雷03',
    'durationSeconds' => 12,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/kan/天候・雷04.mp3',
    'shortName' => '天候・雷04',
    'durationSeconds' => 11,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/kan/天候・雷05.mp3',
    'shortName' => '天候・雷05',
    'durationSeconds' => 5,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/kan/天候・雷06.mp3',
    'shortName' => '天候・雷06',
    'durationSeconds' => 6,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/kan/天候・雷07.mp3',
    'shortName' => '天候・雷07',
    'durationSeconds' => 19,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/kan/天候・雷08.mp3',
    'shortName' => '天候・雷08',
    'durationSeconds' => 14,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/kan/天候・雷09.mp3',
    'shortName' => '天候・雷09',
    'durationSeconds' => 11,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/kan/天候・雷10.mp3',
    'shortName' => '天候・雷10',
    'durationSeconds' => 45,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/kan/天候・風01（草原）.mp3',
    'shortName' => '天候・風01（草原）',
    'durationSeconds' => 30,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/kan/天候・風02（高音）.mp3',
    'shortName' => '天候・風02（高音）',
    'durationSeconds' => 30,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/kan/天候・風03（低音）.mp3',
    'shortName' => '天候・風03（低音）',
    'durationSeconds' => 30,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/kan/天候・風04（草原02）.mp3',
    'shortName' => '天候・風04（草原02）',
    'durationSeconds' => 116,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/kan/天候・風05（柔らかい）.mp3',
    'shortName' => '天候・風05（柔らかい）',
    'durationSeconds' => 36,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/kan/天候・風06（草原03・低音部なし）.mp3',
    'shortName' => '天候・風06（草原03・低音部なし）',
    'durationSeconds' => 30,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/kan/天候・風一吹き（しらけ表現）.mp3',
    'shortName' => '天候・風一吹き（しらけ表現）',
    'durationSeconds' => 5,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/kan/学校のチャイム01.mp3',
    'shortName' => '学校のチャイム01',
    'durationSeconds' => 32,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/kan/学校のチャイム02.mp3',
    'shortName' => '学校のチャイム02',
    'durationSeconds' => 32,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/kan/学校のチャイム03.mp3',
    'shortName' => '学校のチャイム03',
    'durationSeconds' => 30,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/kan/学校のチャイム・ノイズ01.mp3',
    'shortName' => '学校のチャイム・ノイズ01',
    'durationSeconds' => 35,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/kan/学校のチャイム・ノイズ02.mp3',
    'shortName' => '学校のチャイム・ノイズ02',
    'durationSeconds' => 35,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/kan/学校のチャイム・ノイズ03.mp3',
    'shortName' => '学校のチャイム・ノイズ03',
    'durationSeconds' => 32,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/kan/学校のチャイム・遠く（エコー）01.mp3',
    'shortName' => '学校のチャイム・遠く（エコー）01',
    'durationSeconds' => 32,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/kan/学校のチャイム・遠く（エコー）02.mp3',
    'shortName' => '学校のチャイム・遠く（エコー）02',
    'durationSeconds' => 32,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/kan/学校のチャイム・遠く（エコー）03.mp3',
    'shortName' => '学校のチャイム・遠く（エコー）03',
    'durationSeconds' => 30,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/kan/学校の休憩時間.mp3',
    'shortName' => '学校の休憩時間',
    'durationSeconds' => 60,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/kan/小川.mp3',
    'shortName' => '小川',
    'durationSeconds' => 9,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/kan/岩が落ちる.mp3',
    'shortName' => '岩が落ちる',
    'durationSeconds' => 2,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/kan/崖っぷち01.mp3',
    'shortName' => '崖っぷち01',
    'durationSeconds' => 2,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/kan/崖っぷち02.mp3',
    'shortName' => '崖っぷち02',
    'durationSeconds' => 1,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/kan/川01（急流）.mp3',
    'shortName' => '川01（急流）',
    'durationSeconds' => 20,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/kan/川02（なだらか）.mp3',
    'shortName' => '川02（なだらか）',
    'durationSeconds' => 24,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/kan/川03.mp3',
    'shortName' => '川03',
    'durationSeconds' => 90,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/kan/川04.mp3',
    'shortName' => '川04',
    'durationSeconds' => 30,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/kan/川05.mp3',
    'shortName' => '川05',
    'durationSeconds' => 30,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/kan/工事現場.mp3',
    'shortName' => '工事現場',
    'durationSeconds' => 33,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/kan/施設内・ホール内.mp3',
    'shortName' => '施設内・ホール内',
    'durationSeconds' => 37,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/kan/旗ばさばさ.mp3',
    'shortName' => '旗ばさばさ',
    'durationSeconds' => 9,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/kan/旗ばさばさ（より強くにはためく）.mp3',
    'shortName' => '旗ばさばさ（より強くにはためく）',
    'durationSeconds' => 20,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/kan/旗ばさばさ（強めにはためく）.mp3',
    'shortName' => '旗ばさばさ（強めにはためく）',
    'durationSeconds' => 12,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/kan/木のざわめき.mp3',
    'shortName' => '木のざわめき',
    'durationSeconds' => 9,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/kan/木枝が折れる01.mp3',
    'shortName' => '木枝が折れる01',
    'durationSeconds' => 1,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/kan/木枝が折れる02.mp3',
    'shortName' => '木枝が折れる02',
    'durationSeconds' => 3,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/kan/木枝が折れる03.mp3',
    'shortName' => '木枝が折れる03',
    'durationSeconds' => 2,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/kan/木枝が折れる04.mp3',
    'shortName' => '木枝が折れる04',
    'durationSeconds' => 5,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/kan/樹木が倒れる.mp3',
    'shortName' => '樹木が倒れる',
    'durationSeconds' => 8,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/kan/氷山崩壊.mp3',
    'shortName' => '氷山崩壊',
    'durationSeconds' => 23,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/kan/洞窟・洞穴・しずく・風.mp3',
    'shortName' => '洞窟・洞穴・しずく・風',
    'durationSeconds' => 16,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/kan/洞窟内のしずく.mp3',
    'shortName' => '洞窟内のしずく',
    'durationSeconds' => 16,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/kan/海など・水中.mp3',
    'shortName' => '海など・水中',
    'durationSeconds' => 30,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/kan/海・波の音01.mp3',
    'shortName' => '海・波の音01',
    'durationSeconds' => 46,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/kan/海・波の音02（一波）.mp3',
    'shortName' => '海・波の音02（一波）',
    'durationSeconds' => 11,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/kan/海・波の音03.mp3',
    'shortName' => '海・波の音03',
    'durationSeconds' => 42,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/kan/湧き水.mp3',
    'shortName' => '湧き水',
    'durationSeconds' => 27,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/kan/滝.mp3',
    'shortName' => '滝',
    'durationSeconds' => 10,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/kan/災害・土砂崩れ.mp3',
    'shortName' => '災害・土砂崩れ',
    'durationSeconds' => 15,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/kan/災害・土砂崩れ02.mp3',
    'shortName' => '災害・土砂崩れ02',
    'durationSeconds' => 13,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/kan/災害・火山マグマ.mp3',
    'shortName' => '災害・火山マグマ',
    'durationSeconds' => 33,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/kan/災害・火山噴火.mp3',
    'shortName' => '災害・火山噴火',
    'durationSeconds' => 16,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/kan/災害・火災.mp3',
    'shortName' => '災害・火災',
    'durationSeconds' => 15,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/kan/焚き火.mp3',
    'shortName' => '焚き火',
    'durationSeconds' => 41,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/kan/砂崩れ・流砂01.mp3',
    'shortName' => '砂崩れ・流砂01',
    'durationSeconds' => 4,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/kan/砂崩れ・流砂02.mp3',
    'shortName' => '砂崩れ・流砂02',
    'durationSeconds' => 6,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/kan/砂崩れ・流砂03.mp3',
    'shortName' => '砂崩れ・流砂03',
    'durationSeconds' => 11,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/kan/研究室内.mp3',
    'shortName' => '研究室内',
    'durationSeconds' => 7,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/kan/花火・一発.mp3',
    'shortName' => '花火・一発',
    'durationSeconds' => 7,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/kan/花火・連発.mp3',
    'shortName' => '花火・連発',
    'durationSeconds' => 17,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/kan/草木の茂み.mp3',
    'shortName' => '草木の茂み',
    'durationSeconds' => 8,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/kan/街独特の低音.mp3',
    'shortName' => '街独特の低音',
    'durationSeconds' => 36,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/kan/街独特の低音・雨.mp3',
    'shortName' => '街独特の低音・雨',
    'durationSeconds' => 11,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/kan/踏み切り.mp3',
    'shortName' => '踏み切り',
    'durationSeconds' => 10,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/kan/道路.mp3',
    'shortName' => '道路',
    'durationSeconds' => 24,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/kan/道路・雨.mp3',
    'shortName' => '道路・雨',
    'durationSeconds' => 30,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/kan/雨・傘の下.mp3',
    'shortName' => '雨・傘の下',
    'durationSeconds' => 15,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/kan/雨・傘の下（激しい）.mp3',
    'shortName' => '雨・傘の下（激しい）',
    'durationSeconds' => 15,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/kan/雨・路地裏.mp3',
    'shortName' => '雨・路地裏',
    'durationSeconds' => 20,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/kan/駅・ホーム.mp3',
    'shortName' => '駅・ホーム',
    'durationSeconds' => 59,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/kan/駅・ホーム（電車音あり）.mp3',
    'shortName' => '駅・ホーム（電車音あり）',
    'durationSeconds' => 59,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/sen/ぽかぽか殴る01.mp3',
    'shortName' => 'ぽかぽか殴る01',
    'durationSeconds' => 2,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/sen/ぽかぽか殴る02.mp3',
    'shortName' => 'ぽかぽか殴る02',
    'durationSeconds' => 2,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/sen/ぽかぽか殴る・早く01.mp3',
    'shortName' => 'ぽかぽか殴る・早く01',
    'durationSeconds' => 1,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/sen/ぽかぽか殴る・早く02.mp3',
    'shortName' => 'ぽかぽか殴る・早く02',
    'durationSeconds' => 1,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/sen/エアガン・単発.mp3',
    'shortName' => 'エアガン・単発',
    'durationSeconds' => 0,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/sen/エアガン・単発（電動）.mp3',
    'shortName' => 'エアガン・単発（電動）',
    'durationSeconds' => 0,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/sen/エアガン・連発.mp3',
    'shortName' => 'エアガン・連発',
    'durationSeconds' => 1,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/sen/エアガン・連発（電動）.mp3',
    'shortName' => 'エアガン・連発（電動）',
    'durationSeconds' => 2,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/sen/オーラ・気01.mp3',
    'shortName' => 'オーラ・気01',
    'durationSeconds' => 11,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/sen/オーラ・気02.mp3',
    'shortName' => 'オーラ・気02',
    'durationSeconds' => 6,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/sen/オーラ・気03.mp3',
    'shortName' => 'オーラ・気03',
    'durationSeconds' => 6,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/sen/ガラガラ崩れる.mp3',
    'shortName' => 'ガラガラ崩れる',
    'durationSeconds' => 7,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/sen/ゴング.mp3',
    'shortName' => 'ゴング',
    'durationSeconds' => 2,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/sen/スタンガン.mp3',
    'shortName' => 'スタンガン',
    'durationSeconds' => 3,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/sen/スリッパで叩く.mp3',
    'shortName' => 'スリッパで叩く',
    'durationSeconds' => 1,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/sen/ズバン！（ディレイ）.mp3',
    'shortName' => 'ズバン！（ディレイ）',
    'durationSeconds' => 4,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/sen/ダメージ音01.mp3',
    'shortName' => 'ダメージ音01',
    'durationSeconds' => 0,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/sen/ダメージ音02.mp3',
    'shortName' => 'ダメージ音02',
    'durationSeconds' => 0,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/sen/ダメージ音03.mp3',
    'shortName' => 'ダメージ音03',
    'durationSeconds' => 0,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/sen/ドカン！（ディレイ）.mp3',
    'shortName' => 'ドカン！（ディレイ）',
    'durationSeconds' => 1,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/sen/ハリセンで叩く01.mp3',
    'shortName' => 'ハリセンで叩く01',
    'durationSeconds' => 1,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/sen/ハリセンで叩く02.mp3',
    'shortName' => 'ハリセンで叩く02',
    'durationSeconds' => 1,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/sen/ブーメラン.mp3',
    'shortName' => 'ブーメラン',
    'durationSeconds' => 4,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/sen/ホラ貝01.mp3',
    'shortName' => 'ホラ貝01',
    'durationSeconds' => 6,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/sen/ホラ貝02.mp3',
    'shortName' => 'ホラ貝02',
    'durationSeconds' => 4,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/sen/ボクシング・パンチ01.mp3',
    'shortName' => 'ボクシング・パンチ01',
    'durationSeconds' => 1,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/sen/ボクシング・パンチ02.mp3',
    'shortName' => 'ボクシング・パンチ02',
    'durationSeconds' => 0,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/sen/ボクシング・ミット打ち.mp3',
    'shortName' => 'ボクシング・ミット打ち',
    'durationSeconds' => 7,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/sen/ミサイル・隕石・衝突爆発.mp3',
    'shortName' => 'ミサイル・隕石・衝突爆発',
    'durationSeconds' => 30,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/sen/メガホンで叩く01.mp3',
    'shortName' => 'メガホンで叩く01',
    'durationSeconds' => 0,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/sen/メガホンで叩く02.mp3',
    'shortName' => 'メガホンで叩く02',
    'durationSeconds' => 0,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/sen/モールス（SOS）.mp3',
    'shortName' => 'モールス（SOS）',
    'durationSeconds' => 2,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/sen/モールス（作戦開始）.mp3',
    'shortName' => 'モールス（作戦開始）',
    'durationSeconds' => 6,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/sen/モールス（前進）.mp3',
    'shortName' => 'モールス（前進）',
    'durationSeconds' => 4,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/sen/モールス（救助求む）.mp3',
    'shortName' => 'モールス（救助求む）',
    'durationSeconds' => 7,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/sen/モールス（転進）.mp3',
    'shortName' => 'モールス（転進）',
    'durationSeconds' => 3,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/sen/リング・マットに倒れる.mp3',
    'shortName' => 'リング・マットに倒れる',
    'durationSeconds' => 1,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/sen/ロボット・殴る、蹴る01.mp3',
    'shortName' => 'ロボット・殴る、蹴る01',
    'durationSeconds' => 1,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/sen/ロボット・殴る、蹴る02.mp3',
    'shortName' => 'ロボット・殴る、蹴る02',
    'durationSeconds' => 1,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/sen/兵器・物体・高速移動・空気切り裂く.mp3',
    'shortName' => '兵器・物体・高速移動・空気切り裂く',
    'durationSeconds' => 15,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/sen/兵器・物体・高速通過01.mp3',
    'shortName' => '兵器・物体・高速通過01',
    'durationSeconds' => 11,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/sen/兵器・物体・高速通過02.mp3',
    'shortName' => '兵器・物体・高速通過02',
    'durationSeconds' => 7,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/sen/兵器・物体・高速通過03.mp3',
    'shortName' => '兵器・物体・高速通過03',
    'durationSeconds' => 11,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/sen/兵器・物体・高速通過04.mp3',
    'shortName' => '兵器・物体・高速通過04',
    'durationSeconds' => 14,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/sen/刀剣・こすれ合う01.mp3',
    'shortName' => '刀剣・こすれ合う01',
    'durationSeconds' => 2,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/sen/刀剣・こすれ合う02.mp3',
    'shortName' => '刀剣・こすれ合う02',
    'durationSeconds' => 1,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/sen/刀剣・こすれ合う03.mp3',
    'shortName' => '刀剣・こすれ合う03',
    'durationSeconds' => 1,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/sen/刀剣・シュキン！.mp3',
    'shortName' => '刀剣・シュキン！',
    'durationSeconds' => 1,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/sen/刀剣・チャキーン！01.mp3',
    'shortName' => '刀剣・チャキーン！01',
    'durationSeconds' => 1,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/sen/刀剣・チャキーン！02.mp3',
    'shortName' => '刀剣・チャキーン！02',
    'durationSeconds' => 1,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/sen/刀剣・刺す.mp3',
    'shortName' => '刀剣・刺す',
    'durationSeconds' => 0,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/sen/刀剣・刺す02.mp3',
    'shortName' => '刀剣・刺す02',
    'durationSeconds' => 0,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/sen/刀剣・刺す03.mp3',
    'shortName' => '刀剣・刺す03',
    'durationSeconds' => 0,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/sen/刀剣・手裏剣.mp3',
    'shortName' => '刀剣・手裏剣',
    'durationSeconds' => 1,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/sen/刀剣・手裏剣刺さる.mp3',
    'shortName' => '刀剣・手裏剣刺さる',
    'durationSeconds' => 0,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/sen/刀剣・手裏剣刺さる（3連続）.mp3',
    'shortName' => '刀剣・手裏剣刺さる（3連続）',
    'durationSeconds' => 1,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/sen/刀剣・打ち合い01.mp3',
    'shortName' => '刀剣・打ち合い01',
    'durationSeconds' => 2,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/sen/刀剣・打ち合い02.mp3',
    'shortName' => '刀剣・打ち合い02',
    'durationSeconds' => 1,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/sen/刀剣・打ち合い03.mp3',
    'shortName' => '刀剣・打ち合い03',
    'durationSeconds' => 1,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/sen/刀剣・打ち合い04.mp3',
    'shortName' => '刀剣・打ち合い04',
    'durationSeconds' => 1,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/sen/刀剣・打ち合い05.mp3',
    'shortName' => '刀剣・打ち合い05',
    'durationSeconds' => 1,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/sen/刀剣・打ち合い06.mp3',
    'shortName' => '刀剣・打ち合い06',
    'durationSeconds' => 1,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/sen/刀剣・打ち合い07.mp3',
    'shortName' => '刀剣・打ち合い07',
    'durationSeconds' => 1,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/sen/刀剣・打ち合い08.mp3',
    'shortName' => '刀剣・打ち合い08',
    'durationSeconds' => 0,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/sen/刀剣・打ち合い09.mp3',
    'shortName' => '刀剣・打ち合い09',
    'durationSeconds' => 1,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/sen/刀剣・打ち合い10.mp3',
    'shortName' => '刀剣・打ち合い10',
    'durationSeconds' => 1,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/sen/刀剣・打ち合い11.mp3',
    'shortName' => '刀剣・打ち合い11',
    'durationSeconds' => 1,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/sen/刀剣・打ち合い12.mp3',
    'shortName' => '刀剣・打ち合い12',
    'durationSeconds' => 1,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/sen/刀剣・打ち合い13.mp3',
    'shortName' => '刀剣・打ち合い13',
    'durationSeconds' => 1,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/sen/刀剣・打ち合い14.mp3',
    'shortName' => '刀剣・打ち合い14',
    'durationSeconds' => 1,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/sen/刀剣・打ち合い15.mp3',
    'shortName' => '刀剣・打ち合い15',
    'durationSeconds' => 1,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/sen/刀剣・打ち合い16.mp3',
    'shortName' => '刀剣・打ち合い16',
    'durationSeconds' => 1,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/sen/刀剣・打ち合い17.mp3',
    'shortName' => '刀剣・打ち合い17',
    'durationSeconds' => 1,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/sen/刀剣・打ち合い18.mp3',
    'shortName' => '刀剣・打ち合い18',
    'durationSeconds' => 1,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/sen/刀剣・打ち合い19.mp3',
    'shortName' => '刀剣・打ち合い19',
    'durationSeconds' => 1,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/sen/刀剣・打ち合い・大剣.mp3',
    'shortName' => '刀剣・打ち合い・大剣',
    'durationSeconds' => 1,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/sen/刀剣・打ち合い・大剣02.mp3',
    'shortName' => '刀剣・打ち合い・大剣02',
    'durationSeconds' => 1,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/sen/刀剣・打ち合い・大剣03.mp3',
    'shortName' => '刀剣・打ち合い・大剣03',
    'durationSeconds' => 1,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/sen/刀剣・投げナイフ.mp3',
    'shortName' => '刀剣・投げナイフ',
    'durationSeconds' => 0,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/sen/刀剣・抜く.mp3',
    'shortName' => '刀剣・抜く',
    'durationSeconds' => 0,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/sen/刀剣・抜く02.mp3',
    'shortName' => '刀剣・抜く02',
    'durationSeconds' => 0,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/sen/刀剣・抜刀01.mp3',
    'shortName' => '刀剣・抜刀01',
    'durationSeconds' => 0,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/sen/刀剣・抜刀02.mp3',
    'shortName' => '刀剣・抜刀02',
    'durationSeconds' => 1,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/sen/刀剣・抜刀03.mp3',
    'shortName' => '刀剣・抜刀03',
    'durationSeconds' => 2,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/sen/刀剣・抜刀04.mp3',
    'shortName' => '刀剣・抜刀04',
    'durationSeconds' => 1,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/sen/刀剣・斬り刻む01.mp3',
    'shortName' => '刀剣・斬り刻む01',
    'durationSeconds' => 5,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/sen/刀剣・斬り刻む02.mp3',
    'shortName' => '刀剣・斬り刻む02',
    'durationSeconds' => 6,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/sen/刀剣・斬る01.mp3',
    'shortName' => '刀剣・斬る01',
    'durationSeconds' => 0,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/sen/刀剣・斬る02.mp3',
    'shortName' => '刀剣・斬る02',
    'durationSeconds' => 0,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/sen/刀剣・斬る03.mp3',
    'shortName' => '刀剣・斬る03',
    'durationSeconds' => 1,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/sen/刀剣・斬る04.mp3',
    'shortName' => '刀剣・斬る04',
    'durationSeconds' => 1,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/sen/刀剣・斬る05.mp3',
    'shortName' => '刀剣・斬る05',
    'durationSeconds' => 2,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/sen/刀剣・斬る06.mp3',
    'shortName' => '刀剣・斬る06',
    'durationSeconds' => 1,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/sen/刀剣・斬る07.mp3',
    'shortName' => '刀剣・斬る07',
    'durationSeconds' => 0,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/sen/刀剣・斬る08.mp3',
    'shortName' => '刀剣・斬る08',
    'durationSeconds' => 1,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/sen/刀剣・斬る09.mp3',
    'shortName' => '刀剣・斬る09',
    'durationSeconds' => 1,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/sen/刀剣・構える.mp3',
    'shortName' => '刀剣・構える',
    'durationSeconds' => 0,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/sen/刀剣・構える02.mp3',
    'shortName' => '刀剣・構える02',
    'durationSeconds' => 0,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/sen/刀剣・構える03.mp3',
    'shortName' => '刀剣・構える03',
    'durationSeconds' => 0,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/sen/刀剣・空を斬る.mp3',
    'shortName' => '刀剣・空を斬る',
    'durationSeconds' => 2,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/sen/刀剣・突き立てる.mp3',
    'shortName' => '刀剣・突き立てる',
    'durationSeconds' => 1,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/sen/刀剣・落とす.mp3',
    'shortName' => '刀剣・落とす',
    'durationSeconds' => 0,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/sen/刀剣・鍔迫り合い.mp3',
    'shortName' => '刀剣・鍔迫り合い',
    'durationSeconds' => 6,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/sen/刀剣・鞘から抜く・大剣.mp3',
    'shortName' => '刀剣・鞘から抜く・大剣',
    'durationSeconds' => 1,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/sen/刀剣・鞘に収める01.mp3',
    'shortName' => '刀剣・鞘に収める01',
    'durationSeconds' => 1,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/sen/刀剣・鞘に収める02.mp3',
    'shortName' => '刀剣・鞘に収める02',
    'durationSeconds' => 2,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/sen/刀剣・鞘に収める03.mp3',
    'shortName' => '刀剣・鞘に収める03',
    'durationSeconds' => 1,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/sen/刀剣・鞘に収める04.mp3',
    'shortName' => '刀剣・鞘に収める04',
    'durationSeconds' => 3,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/sen/刀剣・鞘に収める05.mp3',
    'shortName' => '刀剣・鞘に収める05',
    'durationSeconds' => 3,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/sen/刀剣・鞘に収める・大剣.mp3',
    'shortName' => '刀剣・鞘に収める・大剣',
    'durationSeconds' => 2,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/sen/刀剣・鞘を握る.mp3',
    'shortName' => '刀剣・鞘を握る',
    'durationSeconds' => 0,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/sen/刀剣・鞘を握る02.mp3',
    'shortName' => '刀剣・鞘を握る02',
    'durationSeconds' => 0,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/sen/刀剣・鞘を握る03.mp3',
    'shortName' => '刀剣・鞘を握る03',
    'durationSeconds' => 0,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/sen/刀剣・飛んできて突き立つ.mp3',
    'shortName' => '刀剣・飛んできて突き立つ',
    'durationSeconds' => 3,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/sen/刀鍛治01.mp3',
    'shortName' => '刀鍛治01',
    'durationSeconds' => 1,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/sen/刀鍛治02（炎音あり）.mp3',
    'shortName' => '刀鍛治02（炎音あり）',
    'durationSeconds' => 3,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/sen/刀鍛治・ふいご.mp3',
    'shortName' => '刀鍛治・ふいご',
    'durationSeconds' => 3,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/sen/刃を研ぐ01.mp3',
    'shortName' => '刃を研ぐ01',
    'durationSeconds' => 23,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/sen/刃を研ぐ02.mp3',
    'shortName' => '刃を研ぐ02',
    'durationSeconds' => 23,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/sen/刃を研ぐ03.mp3',
    'shortName' => '刃を研ぐ03',
    'durationSeconds' => 24,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/sen/刃を研ぐ04.mp3',
    'shortName' => '刃を研ぐ04',
    'durationSeconds' => 25,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/sen/回転01.mp3',
    'shortName' => '回転01',
    'durationSeconds' => 1,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/sen/回転02.mp3',
    'shortName' => '回転02',
    'durationSeconds' => 1,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/sen/回転03.mp3',
    'shortName' => '回転03',
    'durationSeconds' => 1,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/sen/回転04.mp3',
    'shortName' => '回転04',
    'durationSeconds' => 1,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/sen/巨大物体・倒れる.mp3',
    'shortName' => '巨大物体・倒れる',
    'durationSeconds' => 6,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/sen/弓矢・放つ.mp3',
    'shortName' => '弓矢・放つ',
    'durationSeconds' => 3,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/sen/弓矢・矢が刺さる01.mp3',
    'shortName' => '弓矢・矢が刺さる01',
    'durationSeconds' => 0,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/sen/弓矢・矢が刺さる02.mp3',
    'shortName' => '弓矢・矢が刺さる02',
    'durationSeconds' => 0,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/sen/弓矢・矢が刺さる03.mp3',
    'shortName' => '弓矢・矢が刺さる03',
    'durationSeconds' => 2,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/sen/弓矢・矢が生き物に刺さる01.mp3',
    'shortName' => '弓矢・矢が生き物に刺さる01',
    'durationSeconds' => 0,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/sen/弓矢・矢が生き物に刺さる02.mp3',
    'shortName' => '弓矢・矢が生き物に刺さる02',
    'durationSeconds' => 0,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/sen/弓矢・矢が生き物に刺さる03.mp3',
    'shortName' => '弓矢・矢が生き物に刺さる03',
    'durationSeconds' => 0,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/sen/弓矢・矢が生き物に刺さる04.mp3',
    'shortName' => '弓矢・矢が生き物に刺さる04',
    'durationSeconds' => 0,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/sen/戦闘ラッパ.mp3',
    'shortName' => '戦闘ラッパ',
    'durationSeconds' => 4,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/sen/戦闘ラッパ02.mp3',
    'shortName' => '戦闘ラッパ02',
    'durationSeconds' => 4,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/sen/戦闘ラッパ03.mp3',
    'shortName' => '戦闘ラッパ03',
    'durationSeconds' => 4,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/sen/戦闘ラッパ04.mp3',
    'shortName' => '戦闘ラッパ04',
    'durationSeconds' => 3,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/sen/戦闘ラッパ05.mp3',
    'shortName' => '戦闘ラッパ05',
    'durationSeconds' => 4,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/sen/手足・受け止める01.mp3',
    'shortName' => '手足・受け止める01',
    'durationSeconds' => 0,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/sen/手足・受け止める02.mp3',
    'shortName' => '手足・受け止める02',
    'durationSeconds' => 0,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/sen/手足・平手打ち01.mp3',
    'shortName' => '手足・平手打ち01',
    'durationSeconds' => 2,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/sen/手足・平手打ち02.mp3',
    'shortName' => '手足・平手打ち02',
    'durationSeconds' => 1,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/sen/手足・平手打ち03.mp3',
    'shortName' => '手足・平手打ち03',
    'durationSeconds' => 1,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/sen/手足・殴る、蹴る01.mp3',
    'shortName' => '手足・殴る、蹴る01',
    'durationSeconds' => 0,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/sen/手足・殴る、蹴る02.mp3',
    'shortName' => '手足・殴る、蹴る02',
    'durationSeconds' => 0,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/sen/手足・殴る、蹴る03.mp3',
    'shortName' => '手足・殴る、蹴る03',
    'durationSeconds' => 0,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/sen/手足・殴る、蹴る04.mp3',
    'shortName' => '手足・殴る、蹴る04',
    'durationSeconds' => 0,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/sen/手足・殴る、蹴る05.mp3',
    'shortName' => '手足・殴る、蹴る05',
    'durationSeconds' => 0,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/sen/手足・殴る、蹴る06.mp3',
    'shortName' => '手足・殴る、蹴る06',
    'durationSeconds' => 0,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/sen/手足・殴る、蹴る07.mp3',
    'shortName' => '手足・殴る、蹴る07',
    'durationSeconds' => 0,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/sen/手足・殴る、蹴る08.mp3',
    'shortName' => '手足・殴る、蹴る08',
    'durationSeconds' => 0,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/sen/手足・殴る、蹴る09.mp3',
    'shortName' => '手足・殴る、蹴る09',
    'durationSeconds' => 0,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/sen/手足・殴る、蹴る10.mp3',
    'shortName' => '手足・殴る、蹴る10',
    'durationSeconds' => 0,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/sen/手足・殴る、蹴る11.mp3',
    'shortName' => '手足・殴る、蹴る11',
    'durationSeconds' => 1,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/sen/手足・殴る、蹴る12.mp3',
    'shortName' => '手足・殴る、蹴る12',
    'durationSeconds' => 0,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/sen/手足・空振り01.mp3',
    'shortName' => '手足・空振り01',
    'durationSeconds' => 0,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/sen/手足・空振り02.mp3',
    'shortName' => '手足・空振り02',
    'durationSeconds' => 0,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/sen/手足・空振り03.mp3',
    'shortName' => '手足・空振り03',
    'durationSeconds' => 0,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/sen/手足・空振り04.mp3',
    'shortName' => '手足・空振り04',
    'durationSeconds' => 0,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/sen/手足・空振り05.mp3',
    'shortName' => '手足・空振り05',
    'durationSeconds' => 0,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/sen/手足・空振り06.mp3',
    'shortName' => '手足・空振り06',
    'durationSeconds' => 0,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/sen/手足・空振り07.mp3',
    'shortName' => '手足・空振り07',
    'durationSeconds' => 0,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/sen/手足・空振り08.mp3',
    'shortName' => '手足・空振り08',
    'durationSeconds' => 0,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/sen/手足・締め上げる.mp3',
    'shortName' => '手足・締め上げる',
    'durationSeconds' => 2,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/sen/手錠かける.mp3',
    'shortName' => '手錠かける',
    'durationSeconds' => 0,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/sen/捻る01・ゴキッ.mp3',
    'shortName' => '捻る01・ゴキッ',
    'durationSeconds' => 0,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/sen/捻る02・グキッ.mp3',
    'shortName' => '捻る02・グキッ',
    'durationSeconds' => 1,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/sen/木刀・こすれ合う.mp3',
    'shortName' => '木刀・こすれ合う',
    'durationSeconds' => 0,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/sen/木刀・打ち合う.mp3',
    'shortName' => '木刀・打ち合う',
    'durationSeconds' => 0,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/sen/木刀・打撃.mp3',
    'shortName' => '木刀・打撃',
    'durationSeconds' => 0,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/sen/木刀・振る.mp3',
    'shortName' => '木刀・振る',
    'durationSeconds' => 0,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/sen/板割り01.mp3',
    'shortName' => '板割り01',
    'durationSeconds' => 0,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/sen/板割り02.mp3',
    'shortName' => '板割り02',
    'durationSeconds' => 1,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/sen/板割り03.mp3',
    'shortName' => '板割り03',
    'durationSeconds' => 2,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/sen/棍棒・鈍器・殴打01.mp3',
    'shortName' => '棍棒・鈍器・殴打01',
    'durationSeconds' => 0,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/sen/棍棒・鈍器・殴打02.mp3',
    'shortName' => '棍棒・鈍器・殴打02',
    'durationSeconds' => 0,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/sen/棍棒・鈍器・殴打03.mp3',
    'shortName' => '棍棒・鈍器・殴打03',
    'durationSeconds' => 0,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/sen/棍棒・鈍器・殴打04.mp3',
    'shortName' => '棍棒・鈍器・殴打04',
    'durationSeconds' => 0,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/sen/潰れる.mp3',
    'shortName' => '潰れる',
    'durationSeconds' => 0,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/sen/爆破・水上爆発01.mp3',
    'shortName' => '爆破・水上爆発01',
    'durationSeconds' => 4,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/sen/爆破・水上爆発02.mp3',
    'shortName' => '爆破・水上爆発02',
    'durationSeconds' => 4,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/sen/爆破・水中爆発.mp3',
    'shortName' => '爆破・水中爆発',
    'durationSeconds' => 4,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/sen/爆破・爆発01.mp3',
    'shortName' => '爆破・爆発01',
    'durationSeconds' => 2,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/sen/爆破・爆発02.mp3',
    'shortName' => '爆破・爆発02',
    'durationSeconds' => 2,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/sen/爆破・爆発03.mp3',
    'shortName' => '爆破・爆発03',
    'durationSeconds' => 3,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/sen/爆破・爆発04.mp3',
    'shortName' => '爆破・爆発04',
    'durationSeconds' => 3,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/sen/爆破・爆発05.mp3',
    'shortName' => '爆破・爆発05',
    'durationSeconds' => 10,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/sen/爆破・爆発06.mp3',
    'shortName' => '爆破・爆発06',
    'durationSeconds' => 7,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/sen/爆破・爆発07.mp3',
    'shortName' => '爆破・爆発07',
    'durationSeconds' => 5,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/sen/爆破・爆発08.mp3',
    'shortName' => '爆破・爆発08',
    'durationSeconds' => 1,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/sen/爆破・爆発09.mp3',
    'shortName' => '爆破・爆発09',
    'durationSeconds' => 2,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/sen/爆破・爆発10.mp3',
    'shortName' => '爆破・爆発10',
    'durationSeconds' => 7,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/sen/爆破・爆発11.mp3',
    'shortName' => '爆破・爆発11',
    'durationSeconds' => 2,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/sen/爆破・爆発12.mp3',
    'shortName' => '爆破・爆発12',
    'durationSeconds' => 2,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/sen/爆破・爆発13.mp3',
    'shortName' => '爆破・爆発13',
    'durationSeconds' => 2,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/sen/爆破・爆発14.mp3',
    'shortName' => '爆破・爆発14',
    'durationSeconds' => 2,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/sen/爆破・爆発15.mp3',
    'shortName' => '爆破・爆発15',
    'durationSeconds' => 4,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/sen/爆破・爆発16.mp3',
    'shortName' => '爆破・爆発16',
    'durationSeconds' => 8,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/sen/爆破・爆発17.mp3',
    'shortName' => '爆破・爆発17',
    'durationSeconds' => 12,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/sen/爆破・爆発18.mp3',
    'shortName' => '爆破・爆発18',
    'durationSeconds' => 5,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/sen/爆破・爆発19.mp3',
    'shortName' => '爆破・爆発19',
    'durationSeconds' => 4,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/sen/爆破・破砕音01.mp3',
    'shortName' => '爆破・破砕音01',
    'durationSeconds' => 3,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/sen/爆破・破砕音02.mp3',
    'shortName' => '爆破・破砕音02',
    'durationSeconds' => 3,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/sen/特殊攻撃01.mp3',
    'shortName' => '特殊攻撃01',
    'durationSeconds' => 1,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/sen/特殊攻撃02.mp3',
    'shortName' => '特殊攻撃02',
    'durationSeconds' => 1,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/sen/特殊攻撃03.mp3',
    'shortName' => '特殊攻撃03',
    'durationSeconds' => 1,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/sen/特殊攻撃04.mp3',
    'shortName' => '特殊攻撃04',
    'durationSeconds' => 1,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/sen/特殊攻撃05.mp3',
    'shortName' => '特殊攻撃05',
    'durationSeconds' => 1,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/sen/特殊攻撃06.mp3',
    'shortName' => '特殊攻撃06',
    'durationSeconds' => 1,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/sen/瓦割り01.mp3',
    'shortName' => '瓦割り01',
    'durationSeconds' => 1,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/sen/瓦割り02.mp3',
    'shortName' => '瓦割り02',
    'durationSeconds' => 1,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/sen/竹刀・打つ.mp3',
    'shortName' => '竹刀・打つ',
    'durationSeconds' => 1,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/sen/罠・鳴子.mp3',
    'shortName' => '罠・鳴子',
    'durationSeconds' => 5,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/sen/血しぶき・飛び散る01.mp3',
    'shortName' => '血しぶき・飛び散る01',
    'durationSeconds' => 2,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/sen/血しぶき・飛び散る02.mp3',
    'shortName' => '血しぶき・飛び散る02',
    'durationSeconds' => 2,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/sen/血しぶき・飛び散る03.mp3',
    'shortName' => '血しぶき・飛び散る03',
    'durationSeconds' => 2,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/sen/衝突・衝撃（鉄）01.mp3',
    'shortName' => '衝突・衝撃（鉄）01',
    'durationSeconds' => 1,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/sen/衝突・衝撃（鉄）02.mp3',
    'shortName' => '衝突・衝撃（鉄）02',
    'durationSeconds' => 2,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/sen/衝突・衝撃（鉄）03.mp3',
    'shortName' => '衝突・衝撃（鉄）03',
    'durationSeconds' => 2,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/sen/衝突・衝撃（鉄）04.mp3',
    'shortName' => '衝突・衝撃（鉄）04',
    'durationSeconds' => 1,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/sen/衝突・衝撃（鉄）05.mp3',
    'shortName' => '衝突・衝撃（鉄）05',
    'durationSeconds' => 2,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/sen/衝突・衝撃（鉄）06.mp3',
    'shortName' => '衝突・衝撃（鉄）06',
    'durationSeconds' => 2,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/sen/装備.mp3',
    'shortName' => '装備',
    'durationSeconds' => 13,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/sen/西洋剣・サーベル・収める01.mp3',
    'shortName' => '西洋剣・サーベル・収める01',
    'durationSeconds' => 2,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/sen/西洋剣・サーベル・収める02.mp3',
    'shortName' => '西洋剣・サーベル・収める02',
    'durationSeconds' => 2,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/sen/西洋剣・サーベル・収める03.mp3',
    'shortName' => '西洋剣・サーベル・収める03',
    'durationSeconds' => 1,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/sen/西洋剣・サーベル・収める04.mp3',
    'shortName' => '西洋剣・サーベル・収める04',
    'durationSeconds' => 1,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/sen/西洋剣・サーベル・収める05.mp3',
    'shortName' => '西洋剣・サーベル・収める05',
    'durationSeconds' => 1,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/sen/西洋剣・サーベル・打ち合い01.mp3',
    'shortName' => '西洋剣・サーベル・打ち合い01',
    'durationSeconds' => 2,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/sen/西洋剣・サーベル・打ち合い02.mp3',
    'shortName' => '西洋剣・サーベル・打ち合い02',
    'durationSeconds' => 2,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/sen/西洋剣・サーベル・打ち合い03.mp3',
    'shortName' => '西洋剣・サーベル・打ち合い03',
    'durationSeconds' => 2,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/sen/西洋剣・サーベル・打ち合い04.mp3',
    'shortName' => '西洋剣・サーベル・打ち合い04',
    'durationSeconds' => 1,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/sen/西洋剣・サーベル・打ち合い05.mp3',
    'shortName' => '西洋剣・サーベル・打ち合い05',
    'durationSeconds' => 1,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/sen/西洋剣・サーベル・打ち合い06.mp3',
    'shortName' => '西洋剣・サーベル・打ち合い06',
    'durationSeconds' => 1,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/sen/西洋剣・サーベル・抜刀01.mp3',
    'shortName' => '西洋剣・サーベル・抜刀01',
    'durationSeconds' => 2,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/sen/西洋剣・サーベル・抜刀02.mp3',
    'shortName' => '西洋剣・サーベル・抜刀02',
    'durationSeconds' => 2,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/sen/西洋剣・サーベル・抜刀03.mp3',
    'shortName' => '西洋剣・サーベル・抜刀03',
    'durationSeconds' => 1,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/sen/西洋剣・サーベル・抜刀04.mp3',
    'shortName' => '西洋剣・サーベル・抜刀04',
    'durationSeconds' => 1,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/sen/西洋剣・サーベル・抜刀05.mp3',
    'shortName' => '西洋剣・サーベル・抜刀05',
    'durationSeconds' => 2,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/sen/西洋剣・サーベル・構える01.mp3',
    'shortName' => '西洋剣・サーベル・構える01',
    'durationSeconds' => 0,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/sen/西洋剣・サーベル・構える02.mp3',
    'shortName' => '西洋剣・サーベル・構える02',
    'durationSeconds' => 0,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/sen/西洋剣・サーベル・落とす.mp3',
    'shortName' => '西洋剣・サーベル・落とす',
    'durationSeconds' => 1,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/sen/転倒・ズッザー.mp3',
    'shortName' => '転倒・ズッザー',
    'durationSeconds' => 1,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/sen/転倒・倒れる01.mp3',
    'shortName' => '転倒・倒れる01',
    'durationSeconds' => 1,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/sen/転倒・倒れる02.mp3',
    'shortName' => '転倒・倒れる02',
    'durationSeconds' => 1,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/sen/転倒・倒れる03.mp3',
    'shortName' => '転倒・倒れる03',
    'durationSeconds' => 1,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/sen/転倒・倒れる04.mp3',
    'shortName' => '転倒・倒れる04',
    'durationSeconds' => 1,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/sen/転倒・倒れる05.mp3',
    'shortName' => '転倒・倒れる05',
    'durationSeconds' => 2,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/sen/転倒・倒れる06.mp3',
    'shortName' => '転倒・倒れる06',
    'durationSeconds' => 2,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/sen/転倒・倒れる07.mp3',
    'shortName' => '転倒・倒れる07',
    'durationSeconds' => 1,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/sen/転倒・倒れる08.mp3',
    'shortName' => '転倒・倒れる08',
    'durationSeconds' => 1,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/sen/転倒・倒れる09.mp3',
    'shortName' => '転倒・倒れる09',
    'durationSeconds' => 1,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/sen/転倒・倒れる10.mp3',
    'shortName' => '転倒・倒れる10',
    'durationSeconds' => 1,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/sen/転倒・倒れる11.mp3',
    'shortName' => '転倒・倒れる11',
    'durationSeconds' => 1,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/sen/転倒・倒れる12.mp3',
    'shortName' => '転倒・倒れる12',
    'durationSeconds' => 1,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/sen/転倒・柔道の受身.mp3',
    'shortName' => '転倒・柔道の受身',
    'durationSeconds' => 0,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/sen/金だらい・一斗缶01.mp3',
    'shortName' => '金だらい・一斗缶01',
    'durationSeconds' => 3,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/sen/金だらい・一斗缶02.mp3',
    'shortName' => '金だらい・一斗缶02',
    'durationSeconds' => 2,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/sen/金だらい・一斗缶03.mp3',
    'shortName' => '金だらい・一斗缶03',
    'durationSeconds' => 2,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/sen/鉄棒・打撃01.mp3',
    'shortName' => '鉄棒・打撃01',
    'durationSeconds' => 1,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/sen/鉄棒・打撃02.mp3',
    'shortName' => '鉄棒・打撃02',
    'durationSeconds' => 1,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/sen/銃火器・ガトリングガン.mp3',
    'shortName' => '銃火器・ガトリングガン',
    'durationSeconds' => 3,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/sen/銃火器・サイレンサー01.mp3',
    'shortName' => '銃火器・サイレンサー01',
    'durationSeconds' => 0,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/sen/銃火器・サイレンサー02.mp3',
    'shortName' => '銃火器・サイレンサー02',
    'durationSeconds' => 0,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/sen/銃火器・サイレンサー03.mp3',
    'shortName' => '銃火器・サイレンサー03',
    'durationSeconds' => 0,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/sen/銃火器・ショットガン.mp3',
    'shortName' => '銃火器・ショットガン',
    'durationSeconds' => 1,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/sen/銃火器・ショットガンのリロード.mp3',
    'shortName' => '銃火器・ショットガンのリロード',
    'durationSeconds' => 1,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/sen/銃火器・ショットガン＋リロード.mp3',
    'shortName' => '銃火器・ショットガン＋リロード',
    'durationSeconds' => 2,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/sen/銃火器・バルカン.mp3',
    'shortName' => '銃火器・バルカン',
    'durationSeconds' => 3,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/sen/銃火器・ビームサーベル.mp3',
    'shortName' => '銃火器・ビームサーベル',
    'durationSeconds' => 2,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/sen/銃火器・ビームライフル.mp3',
    'shortName' => '銃火器・ビームライフル',
    'durationSeconds' => 1,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/sen/銃火器・マガジンリロード.mp3',
    'shortName' => '銃火器・マガジンリロード',
    'durationSeconds' => 2,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/sen/銃火器・マシンガン01.mp3',
    'shortName' => '銃火器・マシンガン01',
    'durationSeconds' => 2,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/sen/銃火器・マシンガン02.mp3',
    'shortName' => '銃火器・マシンガン02',
    'durationSeconds' => 3,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/sen/銃火器・マシンガン03.mp3',
    'shortName' => '銃火器・マシンガン03',
    'durationSeconds' => 2,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/sen/銃火器・ミサイル01.mp3',
    'shortName' => '銃火器・ミサイル01',
    'durationSeconds' => 3,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/sen/銃火器・ミサイル02.mp3',
    'shortName' => '銃火器・ミサイル02',
    'durationSeconds' => 5,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/sen/銃火器・ミサイル03.mp3',
    'shortName' => '銃火器・ミサイル03',
    'durationSeconds' => 3,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/sen/銃火器・ライフル.mp3',
    'shortName' => '銃火器・ライフル',
    'durationSeconds' => 3,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/sen/銃火器・ライフルのリロード.mp3',
    'shortName' => '銃火器・ライフルのリロード',
    'durationSeconds' => 1,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/sen/銃火器・リボルバーリロード.mp3',
    'shortName' => '銃火器・リボルバーリロード',
    'durationSeconds' => 8,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/sen/銃火器・レーザーガン01.mp3',
    'shortName' => '銃火器・レーザーガン01',
    'durationSeconds' => 1,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/sen/銃火器・レーザーガン02.mp3',
    'shortName' => '銃火器・レーザーガン02',
    'durationSeconds' => 1,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/sen/銃火器・レーザーガン03.mp3',
    'shortName' => '銃火器・レーザーガン03',
    'durationSeconds' => 1,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/sen/銃火器・レーザーガン04.mp3',
    'shortName' => '銃火器・レーザーガン04',
    'durationSeconds' => 2,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/sen/銃火器・レーザーガン05.mp3',
    'shortName' => '銃火器・レーザーガン05',
    'durationSeconds' => 1,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/sen/銃火器・レーザーガン06.mp3',
    'shortName' => '銃火器・レーザーガン06',
    'durationSeconds' => 5,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/sen/銃火器・レーザービーム.mp3',
    'shortName' => '銃火器・レーザービーム',
    'durationSeconds' => 2,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/sen/銃火器・兆弾01.mp3',
    'shortName' => '銃火器・兆弾01',
    'durationSeconds' => 1,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/sen/銃火器・兆弾02.mp3',
    'shortName' => '銃火器・兆弾02',
    'durationSeconds' => 1,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/sen/銃火器・兆弾03.mp3',
    'shortName' => '銃火器・兆弾03',
    'durationSeconds' => 1,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/sen/銃火器・兆弾04.mp3',
    'shortName' => '銃火器・兆弾04',
    'durationSeconds' => 1,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/sen/銃火器・兆弾05.mp3',
    'shortName' => '銃火器・兆弾05',
    'durationSeconds' => 1,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/sen/銃火器・大砲01.mp3',
    'shortName' => '銃火器・大砲01',
    'durationSeconds' => 4,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/sen/銃火器・大砲02.mp3',
    'shortName' => '銃火器・大砲02',
    'durationSeconds' => 2,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/sen/銃火器・大砲03.mp3',
    'shortName' => '銃火器・大砲03',
    'durationSeconds' => 4,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/sen/銃火器・大砲04.mp3',
    'shortName' => '銃火器・大砲04',
    'durationSeconds' => 7,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/sen/銃火器・大砲05.mp3',
    'shortName' => '銃火器・大砲05',
    'durationSeconds' => 3,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/sen/銃火器・大砲06.mp3',
    'shortName' => '銃火器・大砲06',
    'durationSeconds' => 3,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/sen/銃火器・大砲07.mp3',
    'shortName' => '銃火器・大砲07',
    'durationSeconds' => 1,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/sen/銃火器・大砲08.mp3',
    'shortName' => '銃火器・大砲08',
    'durationSeconds' => 3,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/sen/銃火器・大砲09.mp3',
    'shortName' => '銃火器・大砲09',
    'durationSeconds' => 3,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/sen/銃火器・怪光線.mp3',
    'shortName' => '銃火器・怪光線',
    'durationSeconds' => 20,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/sen/銃火器・拳銃01.mp3',
    'shortName' => '銃火器・拳銃01',
    'durationSeconds' => 0,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/sen/銃火器・拳銃02.mp3',
    'shortName' => '銃火器・拳銃02',
    'durationSeconds' => 1,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/sen/銃火器・拳銃03.mp3',
    'shortName' => '銃火器・拳銃03',
    'durationSeconds' => 1,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/sen/銃火器・拳銃04.mp3',
    'shortName' => '銃火器・拳銃04',
    'durationSeconds' => 2,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/sen/銃火器・拳銃05.mp3',
    'shortName' => '銃火器・拳銃05',
    'durationSeconds' => 2,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/sen/銃火器・拳銃06.mp3',
    'shortName' => '銃火器・拳銃06',
    'durationSeconds' => 1,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/sen/銃火器・拳銃07.mp3',
    'shortName' => '銃火器・拳銃07',
    'durationSeconds' => 0,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/sen/銃火器・拳銃08.mp3',
    'shortName' => '銃火器・拳銃08',
    'durationSeconds' => 2,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/sen/銃火器・拳銃09.mp3',
    'shortName' => '銃火器・拳銃09',
    'durationSeconds' => 1,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/sen/銃火器・拳銃10.mp3',
    'shortName' => '銃火器・拳銃10',
    'durationSeconds' => 1,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/sen/銃火器・拳銃11.mp3',
    'shortName' => '銃火器・拳銃11',
    'durationSeconds' => 1,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/sen/銃火器・拳銃12.mp3',
    'shortName' => '銃火器・拳銃12',
    'durationSeconds' => 0,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/sen/銃火器・拳銃13.mp3',
    'shortName' => '銃火器・拳銃13',
    'durationSeconds' => 1,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/sen/銃火器・拳銃14.mp3',
    'shortName' => '銃火器・拳銃14',
    'durationSeconds' => 1,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/sen/銃火器・拳銃15.mp3',
    'shortName' => '銃火器・拳銃15',
    'durationSeconds' => 1,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/sen/銃火器・拳銃・手に取る01.mp3',
    'shortName' => '銃火器・拳銃・手に取る01',
    'durationSeconds' => 1,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/sen/銃火器・拳銃・手に取る02.mp3',
    'shortName' => '銃火器・拳銃・手に取る02',
    'durationSeconds' => 1,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/sen/銃火器・拳銃・放り投げる01.mp3',
    'shortName' => '銃火器・拳銃・放り投げる01',
    'durationSeconds' => 1,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/sen/銃火器・拳銃・放り投げる02.mp3',
    'shortName' => '銃火器・拳銃・放り投げる02',
    'durationSeconds' => 2,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/sen/銃火器・拳銃・落とす01.mp3',
    'shortName' => '銃火器・拳銃・落とす01',
    'durationSeconds' => 0,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/sen/銃火器・拳銃・落とす02.mp3',
    'shortName' => '銃火器・拳銃・落とす02',
    'durationSeconds' => 1,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/sen/銃火器・拳銃・落とす03.mp3',
    'shortName' => '銃火器・拳銃・落とす03',
    'durationSeconds' => 1,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/sen/銃火器・拳銃・落とす04.mp3',
    'shortName' => '銃火器・拳銃・落とす04',
    'durationSeconds' => 1,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/sen/銃火器・拳銃・落とす05.mp3',
    'shortName' => '銃火器・拳銃・落とす05',
    'durationSeconds' => 1,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/sen/銃火器・拳銃構える01.mp3',
    'shortName' => '銃火器・拳銃構える01',
    'durationSeconds' => 0,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/sen/銃火器・拳銃構える02.mp3',
    'shortName' => '銃火器・拳銃構える02',
    'durationSeconds' => 0,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/sen/銃火器・撃鉄上げる.mp3',
    'shortName' => '銃火器・撃鉄上げる',
    'durationSeconds' => 0,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/sen/銃火器・構える01.mp3',
    'shortName' => '銃火器・構える01',
    'durationSeconds' => 0,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/sen/銃火器・構える02.mp3',
    'shortName' => '銃火器・構える02',
    'durationSeconds' => 1,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/sen/銃火器・構える03.mp3',
    'shortName' => '銃火器・構える03',
    'durationSeconds' => 1,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/sen/銃火器・機銃01.mp3',
    'shortName' => '銃火器・機銃01',
    'durationSeconds' => 4,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/sen/銃火器・機銃02（遠）.mp3',
    'shortName' => '銃火器・機銃02（遠）',
    'durationSeconds' => 5,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/sen/銃火器・爆弾投下01（高音）.mp3',
    'shortName' => '銃火器・爆弾投下01（高音）',
    'durationSeconds' => 5,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/sen/銃火器・爆弾投下02（低音）.mp3',
    'shortName' => '銃火器・爆弾投下02（低音）',
    'durationSeconds' => 5,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/sen/銃火器・空撃ち.mp3',
    'shortName' => '銃火器・空撃ち',
    'durationSeconds' => 0,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/sen/銃火器・薬莢・にぎる01.mp3',
    'shortName' => '銃火器・薬莢・にぎる01',
    'durationSeconds' => 1,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/sen/銃火器・薬莢・にぎる02.mp3',
    'shortName' => '銃火器・薬莢・にぎる02',
    'durationSeconds' => 1,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/sen/銃火器・薬莢・掌で転がす.mp3',
    'shortName' => '銃火器・薬莢・掌で転がす',
    'durationSeconds' => 9,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/sen/銃火器・薬莢・落とす（1個）.mp3',
    'shortName' => '銃火器・薬莢・落とす（1個）',
    'durationSeconds' => 0,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/sen/銃火器・薬莢・落とす（複数）01.mp3',
    'shortName' => '銃火器・薬莢・落とす（複数）01',
    'durationSeconds' => 1,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/sen/銃火器・薬莢・落とす（複数）02.mp3',
    'shortName' => '銃火器・薬莢・落とす（複数）02',
    'durationSeconds' => 1,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/sen/銃火器・銃弾・生き物に着弾01.mp3',
    'shortName' => '銃火器・銃弾・生き物に着弾01',
    'durationSeconds' => 1,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/sen/銃火器・銃弾・生き物に着弾02.mp3',
    'shortName' => '銃火器・銃弾・生き物に着弾02',
    'durationSeconds' => 1,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/sen/銃火器・銃弾・生き物に着弾03.mp3',
    'shortName' => '銃火器・銃弾・生き物に着弾03',
    'durationSeconds' => 1,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/sen/銃火器・銃弾・生き物に着弾04.mp3',
    'shortName' => '銃火器・銃弾・生き物に着弾04',
    'durationSeconds' => 1,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/sen/鍋・フライパンで殴る01.mp3',
    'shortName' => '鍋・フライパンで殴る01',
    'durationSeconds' => 3,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/sen/鍋・フライパンで殴る02.mp3',
    'shortName' => '鍋・フライパンで殴る02',
    'durationSeconds' => 4,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/sen/鎖がま01.mp3',
    'shortName' => '鎖がま01',
    'durationSeconds' => 1,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/sen/鎖がま02.mp3',
    'shortName' => '鎖がま02',
    'durationSeconds' => 1,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/sen/鎖・チェーン攻撃.mp3',
    'shortName' => '鎖・チェーン攻撃',
    'durationSeconds' => 1,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/sen/鎧・脱着・装着01.mp3',
    'shortName' => '鎧・脱着・装着01',
    'durationSeconds' => 1,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/sen/鎧・脱着・装着02.mp3',
    'shortName' => '鎧・脱着・装着02',
    'durationSeconds' => 1,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/sen/鎧・脱着・装着03.mp3',
    'shortName' => '鎧・脱着・装着03',
    'durationSeconds' => 1,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/sen/鎧・脱着・装着04.mp3',
    'shortName' => '鎧・脱着・装着04',
    'durationSeconds' => 1,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/sen/電撃・電気攻撃01.mp3',
    'shortName' => '電撃・電気攻撃01',
    'durationSeconds' => 10,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/sen/電撃・電気攻撃02.mp3',
    'shortName' => '電撃・電気攻撃02',
    'durationSeconds' => 10,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/sen/電撃・電気攻撃03.mp3',
    'shortName' => '電撃・電気攻撃03',
    'durationSeconds' => 10,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/sen/電撃・電気攻撃04.mp3',
    'shortName' => '電撃・電気攻撃04',
    'durationSeconds' => 10,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/sen/鞭.mp3',
    'shortName' => '鞭',
    'durationSeconds' => 1,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/sen/鞭02.mp3',
    'shortName' => '鞭02',
    'durationSeconds' => 2,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/sen/鞭03.mp3',
    'shortName' => '鞭03',
    'durationSeconds' => 2,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/sen/鞭04.mp3',
    'shortName' => '鞭04',
    'durationSeconds' => 1,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/sen/飛来01.mp3',
    'shortName' => '飛来01',
    'durationSeconds' => 1,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/sen/飛来02.mp3',
    'shortName' => '飛来02',
    'durationSeconds' => 1,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/sen/骨折る01.mp3',
    'shortName' => '骨折る01',
    'durationSeconds' => 0,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/sen/骨折る02.mp3',
    'shortName' => '骨折る02',
    'durationSeconds' => 0,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'kurage-kosho/button01.mp3',
    'shortName' => 'button01',
    'durationSeconds' => 0,
    'copyright' => '',
  },
  {
    'path' => 'kurage-kosho/button02.mp3',
    'shortName' => 'button02',
    'durationSeconds' => 0,
    'copyright' => '',
  },
  {
    'path' => 'kurage-kosho/button07.mp3',
    'shortName' => 'button07',
    'durationSeconds' => 0,
    'copyright' => '',
  },
  {
    'path' => 'kurage-kosho/button08.mp3',
    'shortName' => 'button08',
    'durationSeconds' => 0,
    'copyright' => '',
  },
  {
    'path' => 'kurage-kosho/button16.mp3',
    'shortName' => 'button16',
    'durationSeconds' => 0,
    'copyright' => '',
  },
  {
    'path' => 'kurage-kosho/button19.mp3',
    'shortName' => 'button19',
    'durationSeconds' => 0,
    'copyright' => '',
  },
  {
    'path' => 'kurage-kosho/button20.mp3',
    'shortName' => 'button20',
    'durationSeconds' => 0,
    'copyright' => '',
  },
  {
    'path' => 'kurage-kosho/button21.mp3',
    'shortName' => 'button21',
    'durationSeconds' => 0,
    'copyright' => '',
  },
  {
    'path' => 'kurage-kosho/button31.mp3',
    'shortName' => 'button31',
    'durationSeconds' => 0,
    'copyright' => '',
  },
  {
    'path' => 'kurage-kosho/button32.mp3',
    'shortName' => 'button32',
    'durationSeconds' => 0,
    'copyright' => '',
  },
  {
    'path' => 'kurage-kosho/button40.mp3',
    'shortName' => 'button40',
    'durationSeconds' => 0,
    'copyright' => '',
  },
  {
    'path' => 'kurage-kosho/button41.mp3',
    'shortName' => 'button41',
    'durationSeconds' => 0,
    'copyright' => '',
  },
  {
    'path' => 'kurage-kosho/button45.mp3',
    'shortName' => 'button45',
    'durationSeconds' => 0,
    'copyright' => '',
  },
  {
    'path' => 'kurage-kosho/button46.mp3',
    'shortName' => 'button46',
    'durationSeconds' => 0,
    'copyright' => '',
  },
  {
    'path' => 'kurage-kosho/button50.mp3',
    'shortName' => 'button50',
    'durationSeconds' => 0,
    'copyright' => '',
  },
  {
    'path' => 'kurage-kosho/button57.mp3',
    'shortName' => 'button57',
    'durationSeconds' => 0,
    'copyright' => '',
  },
  {
    'path' => 'kurage-kosho/button58.mp3',
    'shortName' => 'button58',
    'durationSeconds' => 0,
    'copyright' => '',
  },
  {
    'path' => 'kurage-kosho/button63.mp3',
    'shortName' => 'button63',
    'durationSeconds' => 0,
    'copyright' => '',
  },
  {
    'path' => 'kurage-kosho/magic-ice01.mp3',
    'shortName' => 'magic-ice01',
    'durationSeconds' => 2,
    'copyright' => '',
  },
  {
    'path' => 'kurage-kosho/magic-ice02.mp3',
    'shortName' => 'magic-ice02',
    'durationSeconds' => 2,
    'copyright' => '',
  },
  {
    'path' => 'kurage-kosho/magic-ice03.mp3',
    'shortName' => 'magic-ice03',
    'durationSeconds' => 3,
    'copyright' => '',
  },
  {
    'path' => 'kurage-kosho/magic-wind01.mp3',
    'shortName' => 'magic-wind01',
    'durationSeconds' => 4,
    'copyright' => '',
  },
  {
    'path' => 'kurage-kosho/magic-wind02.mp3',
    'shortName' => 'magic-wind02',
    'durationSeconds' => 3,
    'copyright' => '',
  },
  {
    'path' => 'kurage-kosho/magic-wind03.mp3',
    'shortName' => 'magic-wind03',
    'durationSeconds' => 4,
    'copyright' => '',
  },
  {
    'path' => 'kurage-kosho/magic01.mp3',
    'shortName' => 'magic01',
    'durationSeconds' => 1,
    'copyright' => '',
  },
  {
    'path' => 'kurage-kosho/magic02.mp3',
    'shortName' => 'magic02',
    'durationSeconds' => 1,
    'copyright' => '',
  },
  {
    'path' => 'kurage-kosho/magic03.mp3',
    'shortName' => 'magic03',
    'durationSeconds' => 1,
    'copyright' => '',
  },
  {
    'path' => 'kurage-kosho/magic04.mp3',
    'shortName' => 'magic04',
    'durationSeconds' => 2,
    'copyright' => '',
  },
  {
    'path' => 'kurage-kosho/magic05.mp3',
    'shortName' => 'magic05',
    'durationSeconds' => 1,
    'copyright' => '',
  },
  {
    'path' => 'kurage-kosho/magic06.mp3',
    'shortName' => 'magic06',
    'durationSeconds' => 3,
    'copyright' => '',
  },
  {
    'path' => 'kurage-kosho/magic07.mp3',
    'shortName' => 'magic07',
    'durationSeconds' => 2,
    'copyright' => '',
  },
  {
    'path' => 'kurage-kosho/one01.mp3',
    'shortName' => 'one01',
    'durationSeconds' => 1,
    'copyright' => '',
  },
  {
    'path' => 'kurage-kosho/one04.mp3',
    'shortName' => 'one04',
    'durationSeconds' => 1,
    'copyright' => '',
  },
  {
    'path' => 'kurage-kosho/swords01.mp3',
    'shortName' => 'swords01',
    'durationSeconds' => 2,
    'copyright' => '',
  },
  {
    'path' => 'kurage-kosho/swords02.mp3',
    'shortName' => 'swords02',
    'durationSeconds' => 2,
    'copyright' => '',
  },
  {
    'path' => 'kurage-kosho/swords03.mp3',
    'shortName' => 'swords03',
    'durationSeconds' => 1,
    'copyright' => '',
  },
  {
    'path' => 'kurage-kosho/swords04.mp3',
    'shortName' => 'swords04',
    'durationSeconds' => 1,
    'copyright' => '',
  },
  {
    'path' => 'se-lab/cursor1.mp3',
    'shortName' => 'cursor1',
    'durationSeconds' => 1,
    'copyright' => '',
  },
  {
    'path' => 'se-lab/decision4.mp3',
    'shortName' => 'decision4',
    'durationSeconds' => 2,
    'copyright' => '',
  },
  {
    'path' => 'se-lab/flash-of-light-1.mp3',
    'shortName' => 'flash-of-light-1',
    'durationSeconds' => 1,
    'copyright' => '',
  },
  {
    'path' => 'se-lab/warning1.mp3',
    'shortName' => 'warning1',
    'durationSeconds' => 1,
    'copyright' => '',
  },
];

1;
