use strict;
use utf8;
use warnings;
package SoundEffect;

our @list = [
  {
    'path' => 'On-Jin/kan/お寺の鐘.mp3',
    'shortName' => 'お寺の鐘',
    'durationSeconds' => 20,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/kan/ししおどし.mp3',
    'shortName' => 'ししおどし',
    'durationSeconds' => 1,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/kan/ししおどし（響く）.mp3',
    'shortName' => 'ししおどし（響く）',
    'durationSeconds' => 2,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/kan/オフィスのざわめき.mp3',
    'shortName' => 'オフィスのざわめき',
    'durationSeconds' => 60,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/kan/クラブ・ディスコ・キャバクラ店内.mp3',
    'shortName' => 'クラブ・ディスコ・キャバクラ店内',
    'durationSeconds' => 28,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/kan/ゲームセンター.mp3',
    'shortName' => 'ゲームセンター',
    'durationSeconds' => 31,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/kan/コンビニ・入店チャイム01.mp3',
    'shortName' => 'コンビニ・入店チャイム01',
    'durationSeconds' => 6,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/kan/コンビニ・入店チャイム02.mp3',
    'shortName' => 'コンビニ・入店チャイム02',
    'durationSeconds' => 6,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/kan/チャペルの鐘01.mp3',
    'shortName' => 'チャペルの鐘01',
    'durationSeconds' => 8,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/kan/チャペルの鐘02.mp3',
    'shortName' => 'チャペルの鐘02',
    'durationSeconds' => 19,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/kan/作業現場（足場組み）.mp3',
    'shortName' => '作業現場（足場組み）',
    'durationSeconds' => 30,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/kan/地震・建物内.mp3',
    'shortName' => '地震・建物内',
    'durationSeconds' => 11,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/kan/夜中の情景.mp3',
    'shortName' => '夜中の情景',
    'durationSeconds' => 23,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/kan/大風車.mp3',
    'shortName' => '大風車',
    'durationSeconds' => 28,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/kan/天候・吹雪.mp3',
    'shortName' => '天候・吹雪',
    'durationSeconds' => 14,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/kan/天候・嵐・台風（木々）.mp3',
    'shortName' => '天候・嵐・台風（木々）',
    'durationSeconds' => 28,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/kan/天候・嵐・台風（雨）.mp3',
    'shortName' => '天候・嵐・台風（雨）',
    'durationSeconds' => 28,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/kan/天候・嵐・雷雨.mp3',
    'shortName' => '天候・嵐・雷雨',
    'durationSeconds' => 28,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/kan/天候・強風.mp3',
    'shortName' => '天候・強風',
    'durationSeconds' => 22,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/kan/天候・荒野の風.mp3',
    'shortName' => '天候・荒野の風',
    'durationSeconds' => 29,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/kan/天候・雨01.mp3',
    'shortName' => '天候・雨01',
    'durationSeconds' => 30,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/kan/天候・雨02.mp3',
    'shortName' => '天候・雨02',
    'durationSeconds' => 30,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/kan/天候・雨03.mp3',
    'shortName' => '天候・雨03',
    'durationSeconds' => 30,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/kan/天候・雨04.mp3',
    'shortName' => '天候・雨04',
    'durationSeconds' => 30,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/kan/天候・雨05.mp3',
    'shortName' => '天候・雨05',
    'durationSeconds' => 30,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/kan/天候・雨06.mp3',
    'shortName' => '天候・雨06',
    'durationSeconds' => 30,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/kan/天候・雷01.mp3',
    'shortName' => '天候・雷01',
    'durationSeconds' => 4,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/kan/天候・雷02（遠く）.mp3',
    'shortName' => '天候・雷02（遠く）',
    'durationSeconds' => 65,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/kan/天候・雷03.mp3',
    'shortName' => '天候・雷03',
    'durationSeconds' => 12,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/kan/天候・雷04.mp3',
    'shortName' => '天候・雷04',
    'durationSeconds' => 11,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/kan/天候・雷05.mp3',
    'shortName' => '天候・雷05',
    'durationSeconds' => 5,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/kan/天候・雷06.mp3',
    'shortName' => '天候・雷06',
    'durationSeconds' => 6,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/kan/天候・雷07.mp3',
    'shortName' => '天候・雷07',
    'durationSeconds' => 19,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/kan/天候・雷08.mp3',
    'shortName' => '天候・雷08',
    'durationSeconds' => 14,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/kan/天候・雷09.mp3',
    'shortName' => '天候・雷09',
    'durationSeconds' => 11,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/kan/天候・雷10.mp3',
    'shortName' => '天候・雷10',
    'durationSeconds' => 45,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/kan/天候・風01（草原）.mp3',
    'shortName' => '天候・風01（草原）',
    'durationSeconds' => 30,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/kan/天候・風02（高音）.mp3',
    'shortName' => '天候・風02（高音）',
    'durationSeconds' => 30,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/kan/天候・風03（低音）.mp3',
    'shortName' => '天候・風03（低音）',
    'durationSeconds' => 30,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/kan/天候・風04（草原02）.mp3',
    'shortName' => '天候・風04（草原02）',
    'durationSeconds' => 116,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/kan/天候・風05（柔らかい）.mp3',
    'shortName' => '天候・風05（柔らかい）',
    'durationSeconds' => 36,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/kan/天候・風06（草原03・低音部なし）.mp3',
    'shortName' => '天候・風06（草原03・低音部なし）',
    'durationSeconds' => 30,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/kan/天候・風一吹き（しらけ表現）.mp3',
    'shortName' => '天候・風一吹き（しらけ表現）',
    'durationSeconds' => 5,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/kan/学校のチャイム01.mp3',
    'shortName' => '学校のチャイム01',
    'durationSeconds' => 32,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/kan/学校のチャイム02.mp3',
    'shortName' => '学校のチャイム02',
    'durationSeconds' => 32,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/kan/学校のチャイム03.mp3',
    'shortName' => '学校のチャイム03',
    'durationSeconds' => 30,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/kan/学校のチャイム・ノイズ01.mp3',
    'shortName' => '学校のチャイム・ノイズ01',
    'durationSeconds' => 35,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/kan/学校のチャイム・ノイズ02.mp3',
    'shortName' => '学校のチャイム・ノイズ02',
    'durationSeconds' => 35,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/kan/学校のチャイム・ノイズ03.mp3',
    'shortName' => '学校のチャイム・ノイズ03',
    'durationSeconds' => 32,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/kan/学校のチャイム・遠く（エコー）01.mp3',
    'shortName' => '学校のチャイム・遠く（エコー）01',
    'durationSeconds' => 32,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/kan/学校のチャイム・遠く（エコー）02.mp3',
    'shortName' => '学校のチャイム・遠く（エコー）02',
    'durationSeconds' => 32,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/kan/学校のチャイム・遠く（エコー）03.mp3',
    'shortName' => '学校のチャイム・遠く（エコー）03',
    'durationSeconds' => 30,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/kan/学校の休憩時間.mp3',
    'shortName' => '学校の休憩時間',
    'durationSeconds' => 60,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/kan/小川.mp3',
    'shortName' => '小川',
    'durationSeconds' => 9,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/kan/岩が落ちる.mp3',
    'shortName' => '岩が落ちる',
    'durationSeconds' => 2,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/kan/崖っぷち01.mp3',
    'shortName' => '崖っぷち01',
    'durationSeconds' => 2,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/kan/崖っぷち02.mp3',
    'shortName' => '崖っぷち02',
    'durationSeconds' => 1,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/kan/川01（急流）.mp3',
    'shortName' => '川01（急流）',
    'durationSeconds' => 20,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/kan/川02（なだらか）.mp3',
    'shortName' => '川02（なだらか）',
    'durationSeconds' => 24,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/kan/川03.mp3',
    'shortName' => '川03',
    'durationSeconds' => 90,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/kan/川04.mp3',
    'shortName' => '川04',
    'durationSeconds' => 30,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/kan/川05.mp3',
    'shortName' => '川05',
    'durationSeconds' => 30,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/kan/工事現場.mp3',
    'shortName' => '工事現場',
    'durationSeconds' => 33,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/kan/施設内・ホール内.mp3',
    'shortName' => '施設内・ホール内',
    'durationSeconds' => 37,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/kan/旗ばさばさ.mp3',
    'shortName' => '旗ばさばさ',
    'durationSeconds' => 9,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/kan/旗ばさばさ（より強くにはためく）.mp3',
    'shortName' => '旗ばさばさ（より強くにはためく）',
    'durationSeconds' => 20,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/kan/旗ばさばさ（強めにはためく）.mp3',
    'shortName' => '旗ばさばさ（強めにはためく）',
    'durationSeconds' => 12,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/kan/木のざわめき.mp3',
    'shortName' => '木のざわめき',
    'durationSeconds' => 9,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/kan/木枝が折れる01.mp3',
    'shortName' => '木枝が折れる01',
    'durationSeconds' => 1,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/kan/木枝が折れる02.mp3',
    'shortName' => '木枝が折れる02',
    'durationSeconds' => 3,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/kan/木枝が折れる03.mp3',
    'shortName' => '木枝が折れる03',
    'durationSeconds' => 2,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/kan/木枝が折れる04.mp3',
    'shortName' => '木枝が折れる04',
    'durationSeconds' => 5,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/kan/樹木が倒れる.mp3',
    'shortName' => '樹木が倒れる',
    'durationSeconds' => 8,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/kan/氷山崩壊.mp3',
    'shortName' => '氷山崩壊',
    'durationSeconds' => 23,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/kan/洞窟・洞穴・しずく・風.mp3',
    'shortName' => '洞窟・洞穴・しずく・風',
    'durationSeconds' => 16,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/kan/洞窟内のしずく.mp3',
    'shortName' => '洞窟内のしずく',
    'durationSeconds' => 16,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/kan/海など・水中.mp3',
    'shortName' => '海など・水中',
    'durationSeconds' => 30,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/kan/海・波の音01.mp3',
    'shortName' => '海・波の音01',
    'durationSeconds' => 46,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/kan/海・波の音02（一波）.mp3',
    'shortName' => '海・波の音02（一波）',
    'durationSeconds' => 11,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/kan/海・波の音03.mp3',
    'shortName' => '海・波の音03',
    'durationSeconds' => 42,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/kan/湧き水.mp3',
    'shortName' => '湧き水',
    'durationSeconds' => 27,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/kan/滝.mp3',
    'shortName' => '滝',
    'durationSeconds' => 10,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/kan/災害・土砂崩れ.mp3',
    'shortName' => '災害・土砂崩れ',
    'durationSeconds' => 15,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/kan/災害・土砂崩れ02.mp3',
    'shortName' => '災害・土砂崩れ02',
    'durationSeconds' => 13,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/kan/災害・火山マグマ.mp3',
    'shortName' => '災害・火山マグマ',
    'durationSeconds' => 33,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/kan/災害・火山噴火.mp3',
    'shortName' => '災害・火山噴火',
    'durationSeconds' => 16,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/kan/災害・火災.mp3',
    'shortName' => '災害・火災',
    'durationSeconds' => 15,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/kan/焚き火.mp3',
    'shortName' => '焚き火',
    'durationSeconds' => 41,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/kan/砂崩れ・流砂01.mp3',
    'shortName' => '砂崩れ・流砂01',
    'durationSeconds' => 4,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/kan/砂崩れ・流砂02.mp3',
    'shortName' => '砂崩れ・流砂02',
    'durationSeconds' => 6,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/kan/砂崩れ・流砂03.mp3',
    'shortName' => '砂崩れ・流砂03',
    'durationSeconds' => 11,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/kan/研究室内.mp3',
    'shortName' => '研究室内',
    'durationSeconds' => 7,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/kan/花火・一発.mp3',
    'shortName' => '花火・一発',
    'durationSeconds' => 7,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/kan/花火・連発.mp3',
    'shortName' => '花火・連発',
    'durationSeconds' => 17,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/kan/草木の茂み.mp3',
    'shortName' => '草木の茂み',
    'durationSeconds' => 8,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/kan/街独特の低音.mp3',
    'shortName' => '街独特の低音',
    'durationSeconds' => 36,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/kan/街独特の低音・雨.mp3',
    'shortName' => '街独特の低音・雨',
    'durationSeconds' => 11,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/kan/踏み切り.mp3',
    'shortName' => '踏み切り',
    'durationSeconds' => 10,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/kan/道路.mp3',
    'shortName' => '道路',
    'durationSeconds' => 24,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/kan/道路・雨.mp3',
    'shortName' => '道路・雨',
    'durationSeconds' => 30,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/kan/雨・傘の下.mp3',
    'shortName' => '雨・傘の下',
    'durationSeconds' => 15,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/kan/雨・傘の下（激しい）.mp3',
    'shortName' => '雨・傘の下（激しい）',
    'durationSeconds' => 15,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/kan/雨・路地裏.mp3',
    'shortName' => '雨・路地裏',
    'durationSeconds' => 20,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/kan/駅・ホーム.mp3',
    'shortName' => '駅・ホーム',
    'durationSeconds' => 59,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'On-Jin/kan/駅・ホーム（電車音あり）.mp3',
    'shortName' => '駅・ホーム（電車音あり）',
    'durationSeconds' => 59,
    'copyright' => 'On-Jin ～音人～',
  },
  {
    'path' => 'kurage-kosho/button01.mp3',
    'shortName' => 'button01',
    'durationSeconds' => 0,
    'copyright' => '',
  },
  {
    'path' => 'kurage-kosho/button02.mp3',
    'shortName' => 'button02',
    'durationSeconds' => 0,
    'copyright' => '',
  },
  {
    'path' => 'kurage-kosho/button07.mp3',
    'shortName' => 'button07',
    'durationSeconds' => 0,
    'copyright' => '',
  },
  {
    'path' => 'kurage-kosho/button08.mp3',
    'shortName' => 'button08',
    'durationSeconds' => 0,
    'copyright' => '',
  },
  {
    'path' => 'kurage-kosho/button16.mp3',
    'shortName' => 'button16',
    'durationSeconds' => 0,
    'copyright' => '',
  },
  {
    'path' => 'kurage-kosho/button19.mp3',
    'shortName' => 'button19',
    'durationSeconds' => 0,
    'copyright' => '',
  },
  {
    'path' => 'kurage-kosho/button20.mp3',
    'shortName' => 'button20',
    'durationSeconds' => 0,
    'copyright' => '',
  },
  {
    'path' => 'kurage-kosho/button21.mp3',
    'shortName' => 'button21',
    'durationSeconds' => 0,
    'copyright' => '',
  },
  {
    'path' => 'kurage-kosho/button31.mp3',
    'shortName' => 'button31',
    'durationSeconds' => 0,
    'copyright' => '',
  },
  {
    'path' => 'kurage-kosho/button32.mp3',
    'shortName' => 'button32',
    'durationSeconds' => 0,
    'copyright' => '',
  },
  {
    'path' => 'kurage-kosho/button40.mp3',
    'shortName' => 'button40',
    'durationSeconds' => 0,
    'copyright' => '',
  },
  {
    'path' => 'kurage-kosho/button41.mp3',
    'shortName' => 'button41',
    'durationSeconds' => 0,
    'copyright' => '',
  },
  {
    'path' => 'kurage-kosho/button45.mp3',
    'shortName' => 'button45',
    'durationSeconds' => 0,
    'copyright' => '',
  },
  {
    'path' => 'kurage-kosho/button46.mp3',
    'shortName' => 'button46',
    'durationSeconds' => 0,
    'copyright' => '',
  },
  {
    'path' => 'kurage-kosho/button50.mp3',
    'shortName' => 'button50',
    'durationSeconds' => 0,
    'copyright' => '',
  },
  {
    'path' => 'kurage-kosho/button57.mp3',
    'shortName' => 'button57',
    'durationSeconds' => 0,
    'copyright' => '',
  },
  {
    'path' => 'kurage-kosho/button58.mp3',
    'shortName' => 'button58',
    'durationSeconds' => 0,
    'copyright' => '',
  },
  {
    'path' => 'kurage-kosho/button63.mp3',
    'shortName' => 'button63',
    'durationSeconds' => 0,
    'copyright' => '',
  },
  {
    'path' => 'kurage-kosho/one01.mp3',
    'shortName' => 'one01',
    'durationSeconds' => 1,
    'copyright' => '',
  },
  {
    'path' => 'kurage-kosho/one04.mp3',
    'shortName' => 'one04',
    'durationSeconds' => 1,
    'copyright' => '',
  },
  {
    'path' => 'se-lab/cursor1.mp3',
    'shortName' => 'cursor1',
    'durationSeconds' => 1,
    'copyright' => '',
  },
  {
    'path' => 'se-lab/decision4.mp3',
    'shortName' => 'decision4',
    'durationSeconds' => 2,
    'copyright' => '',
  },
  {
    'path' => 'se-lab/flash-of-light-1.mp3',
    'shortName' => 'flash-of-light-1',
    'durationSeconds' => 1,
    'copyright' => '',
  },
  {
    'path' => 'se-lab/warning1.mp3',
    'shortName' => 'warning1',
    'durationSeconds' => 1,
    'copyright' => '',
  },
];

1;
